/*
*
@author tri.tran on 2/18/19
*
*/

export const ACTION_TYPE = {
    //on internet connection change (true/false)
    ON_INTERNET_CONNECTION_CHANGE: 'ON_INTERNET_CONNECTION_CHANGE',

    //get data information of mobile app
    DO_APP_DATA: 'DO_APP_DATA',
    DO_APP_DATA_SUCCESS: 'DO_APP_DATA_SUCCESS',
    DO_APP_DATA_FAILURE: 'DO_APP_DATA_FAILURE',

    //do login
    DO_LOGIN: 'DO_LOGIN',
    DO_LOGIN_SUCCESS: 'DO_LOGIN_SUCCESS',
    DO_LOGIN_FAILURE: 'DO_LOGIN_FAILURE',

    SHOW_NOTICED_DIALOG: 'SHOW_NOTICED_DIALOG',
    HIDE_NOTICED_DIALOG: 'HIDE_NOTICED_DIALOG',

    //do Logout
    DO_LOGOUT: 'DO_LOGOUT',
    DO_LOGOUT_SUCCESS: 'DO_LOGOUT_SUCCESS',
    DO_LOGOUT_FAILURE: 'DO_LOGOUT_FAILURE',

    DO_AUTO_LOGIN: 'GET_AUTO_LOGIN',

    GET_PROFILE: 'GET_PROFILE',
    GET_PROFILE_SUCCESS: 'GET_PROFILE_SUCCESS',
    GET_PROFILE_FAILURE: 'GET_PROFILE_FAILURE',

    POST_PROFILE: 'POST_PROFILE',
    POST_PROFILE_SUCCESS: 'POST_PROFILE_SUCCESS',
    POST_PROFILE_FAILURE: 'POST_PROFILE_FAILURE',

    GET_PRODUCT_CATEGORIES: 'GET_PRODUCT_CATEGORIES',
    GET_PRODUCT_CATEGORIES_SUCCESS: 'GET_PRODUCT_CATEGORIES_SUCCESS',
    GET_PRODUCT_CATEGORIES_FAILURE: 'GET_PRODUCT_CATEGORIES_FAILURE',

    GET_PRODUCT: 'GET_PRODUCT',
    GET_PRODUCT_SUCCESS: 'GET_PRODUCT_SUCCESS',
    GET_PRODUCT_FAILURE: 'GET_PRODUCT_FAILURE',

    GET_SPECIAL_OFFER: 'GET_SPECIAL_OFFER',
    GET_SPECIAL_OFFER_SUCCESS: 'GET_SPECIAL_OFFER_SUCCESS',
    GET_SPECIAL_OFFER_FAILURE: 'GET_SPECIAL_OFFER_FAILURE',

    DO_LIKE_PRODUCT: 'DO_LIKE_PRODUCT',
    DO_LIKE_PRODUCT_SUCCESS: 'DO_LIKE_PRODUCT_SUCCESS',
    DO_LIKE_PRODUCT_FAILURE: 'DO_LIKE_PRODUCT_FAILURE',

    DO_SEARCH: 'DO_SEARCH',
    DO_SEARCH_SUCCESS: 'DO_SEARCH_SUCCESS',
    DO_SEARCH_FAILURE: 'DO_SEARCH_FAILURE',

    GET_STORES: 'GET_STORES',
    GET_STORES_SUCCESS: 'GET_STORES_SUCCESS',
    GET_STORES_FAILURE: 'GET_STORES_FAILURE',

    CALL_GOOGLE_MAP_API: 'CALL_GOOGLE_MAP_API',
    CALL_GOOGLE_MAP_API_SUCCESS: 'CALL_GOOGLE_MAP_API_SUCCESS',
    CALL_GOOGLE_MAP_API_FAILURE: 'CALL_GOOGLE_MAP_API_FAILURE',

    GET_VOUCHERS: 'GET_VOUCHERS',
    GET_VOUCHERS_SUCCESS: 'GET_VOUCHERS_SUCCESS',
    GET_VOUCHERS_FAILURE: 'GET_VOUCHERS_FAILURE',

    GET_MY_REWARDS: 'GET_MY_REWARDS',
    GET_MY_REWARDS_SUCCESS: 'GET_MY_REWARDS_SUCCESS',
    GET_MY_REWARDS_FAILURE: 'GET_MY_REWARDS_FAILURE',

    CHANGE_AVAILABLE_VOUCHERS: 'CHANGE_AVAILABLE_VOUCHERS',
    CHANGE_AVAILABLE_VOUCHERS_SUCCESS: 'CHANGE_AVAILABLE_VOUCHERS_SUCCESS',
    CHANGE_AVAILABLE_VOUCHERS_FAILURE: 'CHANGE_AVAILABLE_VOUCHERS_FAILURE',

    GET_HISTORY_VOUCHERS: 'GET_HISTORY_VOUCHERS',
    GET_HISTORY_VOUCHERS_SUCCESS: 'GET_HISTORY_VOUCHERS_SUCCESS',
    GET_HISTORY_VOUCHERS_FAILURE: 'GET_HISTORY_VOUCHERS_FAILURE',

    OPEN_MESSAGE: 'OPEN_MESSAGE',
    OPEN_MESSAGE_SUCCESS: 'OPEN_MESSAGE_SUCCESS',
    OPEN_MESSAGE_FAILURE: 'OPEN_MESSAGE_FAILURE',

    CLOSE_MESSAGE: 'CLOSE_MESSAGE',
    CLOSE_MESSAGE_SUCCESS: 'CLOSE_MESSAGE_SUCCESS',
    CLOSE_MESSAGE_FAILURE: 'CLOSE_MESSAGE_FAILURE',

}
